name: DeploySnowflakeChanges

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install schemachange
        run: pip install schemachange

      - name: Create connections.toml
        run: |
          {
            echo "[snowflake]"
            echo "account = \"${{ secrets.SF_ACCOUNT }}\""
            echo "user = \"${{ secrets.SF_USERNAME }}\""
            echo "password = \"${{ secrets.SF_PASSWORD }}\""
            echo "role = \"${{ secrets.SF_ROLE }}\""
            echo "warehouse = \"${{ secrets.SF_WAREHOUSE }}\""
            echo "database = \"${{ secrets.SF_DATABASE }}\""
            echo "schema = \"${{ secrets.SF_SCHEMA }}\""
          } > connections.toml


      - name: Run schemachange
        run: |
          schemachange -f deploy --connections-file-path connections.toml --connection-name snowflake
