name: snowflake-migration-demo

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'  # Only trigger when files in 'deploy/' change
  workflow_dispatch:  # Allow manual runs

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python 3.8
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 3. Create connections.toml (stores Snowflake credentials)
      - name: Create Snowflake connection config
        run: |
          cat <<EOF > connections.toml
          [snowflake]
          account = "${{ secrets.SF_ACCOUNT }}"
          user = "${{ secrets.SF_USERNAME }}"
          password = "${{ secrets.SF_PASSWORD }}"
          role = "${{ secrets.SF_ROLE }}"
          warehouse = "${{ secrets.SF_WAREHOUSE }}"
          database = "${{ secrets.SF_DATABASE }}"
          EOF

      # 4. Install schemachange and run migrations
      - name: Run schemachange
        run: |
          pip install schemachange
          schemachange deploy \
            -f $GITHUB_WORKSPACE/deploy \  # Path to your SQL scripts
            -c "${{ secrets.SF_DATABASE }}.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table
