name: snowflake-migration-demo

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run schemachange
        run: |
          pip install schemachange
          schemachange deploy \
            -f $GITHUB_WORKSPACE/deploy \
            -a "${{ secrets.SF_ACCOUNT }}" \
            -u "${{ secrets.SF_USERNAME }}" \
            -p "${{ secrets.SF_PASSWORD }}" \
            -r "${{ secrets.SF_ROLE }}" \
            -w "${{ secrets.SF_WAREHOUSE }}" \
            -d "${{ secrets.SF_DATABASE }}" \
            -c "${{ secrets.SF_DATABASE }}.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table
